[workspace]
members = ["test/e2e/fixture/zomes/foo", "test/e2e/fixture2/coordinator2"]

resolver = "2"

[profile.dev]
opt-level = "z"

[workspace.dependencies]
hdk = "0.6.1-rc.0"
holochain_serialized_bytes = "0.0.56"
